modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="mcpaintball" #mandatory
version="1.0.0" #mandatory
displayName="MC Paintball" #mandatory
logoFile="examplemod.png" #optional
credits="" #optional
authors="Multicoder" #optional
description='''Minecraft paintball mod adds a vanilla way to paintball and have fun with friends.'''
[[dependencies.mcpaintball]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[44,)" #mandatory
    ordering="NONE"
   side="BOTH"
[[dependencies.mcpaintball]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
