modLoader="javafml"
loaderVersion="[44,)"
license="MIT"
[[mods]]
modId="mcpaintball"
version="1.0.0-Beta2"
displayName="MC Paintball"
authors="Multicoder"
description='''Minecraft paintball mod adds a vanilla way to paintball and have fun with friends.'''
[[dependencies.mcpaintball]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
   side="BOTH"
[[dependencies.mcpaintball]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
